### PR TITLE
Overhaul how we retrieve the client IP

### LINKED ISSUE #286: get_client_ip may fail if HTTP_FORWARDED doesn’t contain an IP address
Since the `HTTP_FORWARDED` doesn’t necessarily contains an IP address, the function `get_client_ip` may fail if there is just a `HTTP_FORWARDED` and the `REMOTE_ADDR` with the following values:

```
Array
(
    [REMOTE_ADDR] => 127.0.0.1
    [HTTP_FORWARDED] => proto=https
)
```

Since `HTTP_FORWARDED` is checked before `REMOTE_ADDR`, the further sanitation recognize that there is no IP address in it and thus fails. In this case, every comment gets marked as spam even if it isn’t.

I would recommend to change the sorting of the check so that `REMOTE_ADDR` gets checked before `HTTP_FORWARDED`, which may be available but without the IP address as is’t not necessarily available in the `HTTP_FORWARDED` variable.

### PR DESCRIPTION
**Pull request by websupporter**
Fixes #286
Based of #297 

In order to solve the problem in #286 we now run through all possibilities where we could get an IP. The new `_sanitize_ip()` method sanitizes what we might have got from those sources. If we haven't received a valid IP, we use the default `$_SERVER['REMOTE_ADDR']` to detect the clients IP.

Just reordering, as suggested in #286 didnt feel sufficient as the REMOTE_ADDR itself might contain a "wrong" address, e.g. the varnish address or sth else.

### CODE REVIEW

File: antispam_bee.php [hunk 1]
```diff
@@ -2348,32 +2350,50 @@ public static function get_client_ip() {
...
-				$ip,
+			return (string) filter_var(
+				$raw_ip,
 				FILTER_VALIDATE_IP
 			);
 		}
 
-		return preg_replace(
+		return (string) preg_replace(
 			'/[^0-9a-f:\., ]/si',
```
Comment (stklcode) [inline antispam_bee.php]: Comma should no longer occur at this point and escaping the dot within the character class is redundant.

Comment (websupporter) [reply antispam_bee.php]: good catch
